// Copyright (c) Meta Platforms, Inc. and affiliates.
// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated by scripts/gen_dwarf_constants.py.

#include <stdio.h>

#include "dwarf_constants.h"

#define X(name, value) case name: return #name;

const char *dw_tag_str(int value, char buf[static DW_TAG_STR_BUF_LEN])
{
	switch (value) {
	DW_TAG_DEFINITIONS
	default:
		snprintf(buf, DW_TAG_STR_BUF_LEN, DW_TAG_STR_UNKNOWN_FORMAT, value);
		return buf;
	}
}

#undef X
