.\" Modified Thu Sep 5 2017 by Ben Woodard <woodard@redhat.com>
.\"
.TH ELF_UPDATE 3 2017-09-05 "Libelf" "Libelf Programmer's Manual"
.SH NAME
elf_update \- update an ELF descriptor
.nf
.SH SYNOPSIS
.B #include <libelf.h>
.sp
.BI "off_t elf_update (Elf *" elf ", Elf_Cmd " cmd ");"
.fi
.SH DESCRIPTION
The
.BR elf_update ()
